// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNdb-sI4g1DckYCOt9TuqNMKWfmZLz9Jc',
    appId: '1:88957510561:web:531c17d59e3cc6ea9261e0',
    messagingSenderId: '88957510561',
    projectId: 'chat-app-89030',
    authDomain: 'chat-app-89030.firebaseapp.com',
    storageBucket: 'chat-app-89030.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHYrgm_tfAMt1PHhx1i-_cVtvbOn993AI',
    appId: '1:88957510561:android:2b9e5ef831e2fa3b9261e0',
    messagingSenderId: '88957510561',
    projectId: 'chat-app-89030',
    storageBucket: 'chat-app-89030.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs2GLN1pNMW69qqlfF3KIOMUrsg5ZW8Xk',
    appId: '1:88957510561:ios:b99ad98fd74cab559261e0',
    messagingSenderId: '88957510561',
    projectId: 'chat-app-89030',
    storageBucket: 'chat-app-89030.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs2GLN1pNMW69qqlfF3KIOMUrsg5ZW8Xk',
    appId: '1:88957510561:ios:dfc56b4c660724769261e0',
    messagingSenderId: '88957510561',
    projectId: 'chat-app-89030',
    storageBucket: 'chat-app-89030.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
